version: '1'
services: 
  db:
    image: postgres
    restart: on-failure
    environment: 
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - db_network
    ports: 
      - "${POSTGRES_PORT}:5432"

  nestjs:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: nestjs-rest-service
    restart: on-failure
    environment: 
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=false
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_EXPIRES=${TOKEN_EXPIRE_TIME}
      - APP_PORT=${PORT}
      - LVL_LOG=${LVL_LOG}
    ports: 
      - "${PORT}:${PORT}" # expose-to-the-world : only-in-the-docker
    container_name: nest-rest-service
    depends_on: 
      - db
    networks:
      - db_network
    volumes: 
      - .:/app
      - /app/node_modules   
      - migrations:/usr/app/migrations 

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports: 
      - "8080:80"
    volumes: 
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on: 
      - db
    networks:
      - db_network
volumes:
  pgdata:
  pgadmin-data:
  migrations:

networks:
  db_network:
    driver: bridge